

replicaCount: 1

image:
  repository: amagdi888/my-repo:hello-app

labels:
  app: web-app
  type: frontend


service:
  protocol: TCP
  type: NodePort
  port: 8000
  nodePort: 30080
  labels:
    name: webapp-service

deployment:
  port: 8000

